 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: git submodule update --recursive --init
       - run: msbuild -t:restore -t:build
       - run: dotnet test --no-build